name: firebase_flutter
version: 0.0.4
description: Firebase integration with Flutter
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: http://flutter.io/
environment:
  sdk: '>=1.0.0 <2.0.0'
